#plot 3
my_data<- read.table("household_power_consumption.txt",sep = ";",header = TRUE,na.strings = c("?"))
my_subset_data<- subset(my_data,Date %in% c("1/2/2007","2/2/2007") )
my_subset_data$Date<-strptime(paste(my_subset_data$Date, my_subset_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot3.png", width=480, height=480)
with(my_subset_data,{plot(Date,Sub_metering_1,type="l",xlab="",ylab = "Energy Submetering")
  lines(Date,Sub_metering_2,type="l",col="red")
  lines(Date,Sub_metering_3,type="l",col="blue")
  legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2, col=c("black", "red", "blue"))})
dev.off()