#plot 4
my_data<- read.table("household_power_consumption.txt",sep = ";",header = TRUE,na.strings = c("?"))
my_subset_data<- subset(my_data,Date %in% c("1/2/2007","2/2/2007") )
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
with(my_subset_data,{plot(Date,Global_active_power,type = "l",ylab="Global Active Power")
  plot(Date,Voltage,type ="l",xlab="datetime",ylab="Voltage")
  plot(Date,Sub_metering_1,type="l",xlab="",ylab = "Energy Submetering")
  lines(Date,Sub_metering_2,type="l",col="red")
  lines(Date,Sub_metering_3,type="l",col="blue")
  legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col=c("black", "red", "blue"))
  plot(Date,Global_reactive_power,type = "l",xlab="datetime")
})
dev.off()
